ci: update check title step

diff --git a/.github/workflows/enforce_pr_format.yaml b/.github/workflows/enforce_pr_format.yaml
--- a/.github/workflows/enforce_pr_format.yaml
+++ b/.github/workflows/enforce_pr_format.yaml
@@ -36,9 +36,14 @@ jobs:
       - name: Check title
         run: |
             title=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')
-            if [[ ! $title =~ ^feat: #[0-9]+$ ]]; then
-            echo "::error::Pull request title does not follow the required 'feat: #<issue_number>' format"
-            exit 1
+
+            # Define allowed Conventional Commit types
+            allowed_types="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
+            
+            # Check if title matches the pattern: <type>: #<issue_number>
+            if [[ ! $title =~ ^($allowed_types): #[0-9]+$ ]]; then
+              echo "::error::Pull request title does not follow the required '<Conventional Commit type>: #<issue_number>' format"
+              exit 1
             fi
 
       - name: Check description
